import { createSlice } from "@reduxjs/toolkit";

interface NotifyState {
  loading: boolean;
  data: string[];
  sound: boolean;
}

const initialState: NotifyState = {
  loading: false,
  data: [],
  sound: false,
};

const NotifyState = createSlice({
  name: "notify",
  initialState,
  reducers: {
    reset: () => initialState,
    setIsLoading: (state, action) => {
      state.loading = action.payload;
    },
    setNotifyData: (state, action) => {
      state.data = action.payload;
    },
  },
});

// Export the action creators generated by createSlice
export const { reset, setIsLoading, setNotifyData } = NotifyState.actions;

// Export the reducer function generated by createSlice
export default NotifyState.reducer;
